---
deployment:
  tasks:
    - export DEPLOYPATH=/home/auxdqnplkyiy/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R academic $DEPLOYPATH
    - /bin/cp -R engineering $DEPLOYPATH
